<?xml version="1.0"?>
<package format="3">
  <name>scope_nav</name>
  <version>0.0.0</version>
  <description>The scope_nav package</description>

  <maintainer email="xzt@todo.todo">xzt</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Only keep runtime deps you actually use -->
  <!-- If you have ROS 2 C++ nodes in THIS package, use rclcpp -->
  <exec_depend>rclcpp</exec_depend>

  <!-- If you have ROS 2 Python nodes/scripts in THIS package, use rclpy -->
  <exec_depend>rclpy</exec_depend>

  <!-- Runtime dependencies for Python nodes -->
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>scope_msgs</exec_depend>
  <exec_depend>people_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>tf_transformations</exec_depend>
  <exec_depend>message_filters</exec_depend>
  <exec_depend>cv_bridge</exec_depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

