model:
  base_learning_rate: 1.0e-04
  target: models.diffusion.ddpm.PredOccLatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    log_every_t: 200
    timesteps: 1000
    image_size: 16
    channels: 2
    conditioning_key: concat
    parameterization: eps
    monitor: val/loss
    use_ema: True
    convlstm_hidden_dim: 33
    scale_factor: 0.374106

    first_stage_ckpt_path: "./pretrained_models/first_stage_models/AE/v7.0/model.ckpt"

    first_stage_config:
      target: models.autoencoder.SequenceAutoencoderKL
      params:
        embed_dim: 2
        seq_len: 10
        monitor: val/total_loss
        in_channels: 1
        out_ch: 1
        resolution: 64
        num_hiddens: 128
        num_residual_layers: 2
        num_residual_hiddens: 64
        lossconfig:
          target: modules.losses.AELoss
          params:
            kl_weight: 1.0e-06

    cond_stage_config: 
      target: torch.nn.Identity 

    scheduler_config:
      target: lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 10000 ]
        cycle_lengths: [ 10000000000000 ]
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]


    unet_config:
      target: modules.diffusionmodules.unet_latent_shift.UNetModel
      params:
        image_size: 16
        in_channels: 35  # 34 : x_noisy(2) + cond(32) # 4 : x_noisy(2) + cond(2)
        out_channels: 2
        model_channels: 128
        attention_resolutions: [4]
        num_res_blocks: 1
        channel_mult: [1, 2]
        num_heads: 8
        use_temporal_shift: True
        num_frames: 10
        shift_fold_div: 3
        use_spatial_transformer: False
        use_checkpoint: True
        legacy: False
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 4
    test:
      target: data.dataloader.PredOccDataset
      params:
        data_root: "../data/OGM-datasets/OGM-Turtlebot2/test/"
        split: "test"
        
lightning:
  trainer:
    max_epochs: 100
    check_val_every_n_epoch: 1

  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 50
    
    train_loss_epoch_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        filename: "trainloss-{epoch:06d}"
        monitor: "train/loss_epoch"
        save_top_k: 5
        save_last: false


  modelcheckpoint:
    params:
      monitor: "val/loss"
      save_top_k: 10
      save_last: true