model:
  base_learning_rate: 1.0e-04
  target: models.ddpm.PredOccLatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    log_every_t: 200
    timesteps: 1000
    image_size: 16
    channels: 2
    conditioning_key: concat
    parameterization: eps
    monitor: val/loss
    use_ema: True
    convlstm_hidden_dim: 33
    scale_factor: 0.374106

    first_stage_ckpt_path: "/home/glab/dyna_ws/src/scope_nav/scope_nav/src/model/predocc_diff/ae7.0/model.pth"

    first_stage_config:
      target: models.autoencoder.SequenceAutoencoderKL
      params:
        embed_dim: 2
        seq_len: 10
        monitor: val/total_loss
        in_channels: 1
        out_ch: 1
        resolution: 64
        num_hiddens: 128
        num_residual_layers: 2
        num_residual_hiddens: 64
        lossconfig:
          target: losses.AELoss
          params:
            kl_weight: 1.0e-06

    cond_stage_config: 
      target: torch.nn.Identity 

    scheduler_config:
      target: lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 10000 ]
        cycle_lengths: [ 10000000000000 ]
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]


    unet_config:
      target: diffusionmodules.unet_latent_shift.UNetModel
      params:
        image_size: 16
        in_channels: 35  # 34 : x_noisy(2) + cond(32) # 4 : x_noisy(2) + cond(2)
        out_channels: 2
        model_channels: 128
        attention_resolutions: [4]
        num_res_blocks: 1
        channel_mult: [1, 2]
        num_heads: 8
        use_temporal_shift: True
        num_frames: 10
        shift_fold_div: 3
        use_spatial_transformer: False
        use_checkpoint: True
        legacy: False